version: '3.8'

services:
  bff-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sanos_bff_gateway
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MS_MASCOTAS_URL: ${URL_MASCOTAS}
      MS_GEOLOCALIZACION_URL: ${URL_GEOLOCALIZACION}
      # Pasamos la URL de Clerk al contenedor
      CLERK_ISSUER_URI: ${CLERK_ISSUER_URI}
    networks:
      - sanos-network

networks:
  sanos-network:
    external: true
