version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sanos-api-gateway
    restart: unless-stopped
    env_file:               
      - .env                 
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}" # Único componente expuesto al mundo exterior
    environment:
      # Dejamos solo lo estrictamente necesario si requieres transformaciones dinámicas,
      # el resto se lee automáticamente desde el archivo .env de forma limpia.
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - sanos-network

networks:
  sanos-network:
    external: true