spring.application.name=bff-gateway
server.port=8082

# Estas rutas ESTÁN CORRECTAS para Docker
microservicio.mascotas.url=http://sanos_ms_mascotas:8080/api/v1/mascotas
microservicio.geolocalizacion.url=http://sanos_ms_geolocalizacion:8081/api/v1/geolocalizacion

# CAMBIO AQUÍ: Comentamos Clerk temporalmente para que la API pueda levantar sin errores de seguridad
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://tu-clerk-issuer-url.clerk.accounts.dev/