spring.application.name=bff-gateway

server.servlet.context-path=/api/bff/v1


server.port=${SERVER_PORT:8082}
microservicio.mascotas.url=${MS_MASCOTAS_URL:http://localhost:8080}/api/v1/mascotas
microservicio.geolocalizacion.url=${MS_GEOLOCALIZACION_URL:http://localhost:8081}/api/v1/geolocalizacion

# Configuración de Seguridad con Clerk
spring.security.oauth2.resourceserver.jwt.issuer-uri=${CLERK_ISSUER_URL}


spring.cloud.gateway.mvc.routes[0].id=gestormascotas
spring.cloud.gateway.mvc.routes[0].uri=${MS_MASCOTAS_URL:http://localhost:8080}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/bff/v1/mascotas/**
spring.cloud.gateway.mvc.routes[0].filters[0]=StripPrefix=3

spring.cloud.gateway.mvc.routes[1].id=geolocalizacion
spring.cloud.gateway.mvc.routes[1].uri=${MS_GEOLOCALIZACION_URL:http://localhost:8081}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/bff/v1/geolocalizacion/**
spring.cloud.gateway.mvc.routes[1].filters[0]=StripPrefix=3