spring.application.name=api-gateway

server.port=${SERVER_PORT:8082}

# URLs de microservicios
microservicio.mascotas.url=${MS_MASCOTAS_URL:http://localhost:8080}/api/v1/mascotas
microservicio.geolocalizacion.url=${MS_GEOLOCALIZACION_URL:http://localhost:8081}/api/v1/geolocalizacion

# Autenticación con Clerk (OAuth2 Resource Server / JWT)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${CLERK_ISSUER_URL}

# Rutas del Gateway
spring.cloud.gateway.mvc.routes[0].id=gestormascotas
spring.cloud.gateway.mvc.routes[0].uri=${MS_MASCOTAS_URL:http://localhost:8080}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/mascotas/**
spring.cloud.gateway.mvc.routes[0].filters[0]=StripPrefix=0

spring.cloud.gateway.mvc.routes[1].id=geolocalizacion
spring.cloud.gateway.mvc.routes[1].uri=${MS_GEOLOCALIZACION_URL:http://localhost:8081}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/geolocalizacion/**
spring.cloud.gateway.mvc.routes[1].filters[0]=StripPrefix=0